### ISSUE TITLE
Update mion-testing documentation

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-testing#1]
The information on package tests and runtime tests needs to be update, with information specific to mion will be added in the near future.

**Comment by johntoomey** [comment]
this is a duplicate of the test plan issue - @kprosise to check that that is tracked somewhere else and close this out

**Comment by johntoomey** [comment]
this is the original task i think: https://github.com/NetworkGradeLinux/meta-mion/issues/8

**Comment by johntoomey** [comment]
i think this is covered by the test plan issue https://github.com/NetworkGradeLinux/mion-docs/issues/168
